# Site settings
title: Kelly Phalen
email: kelly.phalen@yahoo.com
url: https://example.github.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#8dc3c4'
  links: '#ffffff'

# Footer settings
footer: Kelly Phalen

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: https://stackoverflow.com/users/11803965/kelly-phalen
  - title: linkedin
    url: https://linkedin.com/in/kelly-phalen
  - title: github
    url: https://github.com/kelly-phalen

# Build settings
markdown: kramdown
permalink: pretty
